name: baredex
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  timeline_list: ^0.0.5
  simple_animations: ^1.3.11
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  logger: ^0.8.3
  provider: ^4.0.4
  get_it: ^4.0.1
  transparent_image: ^1.0.0
  cached_network_image: ^2.1.0+1
  keyboard_avoider: ^0.1.2
  intl: ^0.16.1
  dropdown_search: ^0.2.8
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.8.1
  badges: ^1.1.1
  basic_utils: ^2.5.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  device_preview: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^3.0.9


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/ali-hasan.png
    - assets/images/daisy-murphy.png
    - assets/images/female-avatar.png
    - assets/images/male-avatar-1.png
    - assets/images/male-avatar-2.png
    - assets/images/nnena.png
    - assets/images/nual.png
    - assets/images/profile.png
    - assets/images/profil2.png
    - assets/images/sara.png
    - assets/images/stevan.png
    - assets/images/aplle-pay.png
    - assets/images/baredex-credit.png
    - assets/images/visa.png
    - assets/images/visa-icon.png
    - assets/images/mastercard-icon.png
    - assets/images/mada-icon.png
    - assets/images/apple-pay-icon.png
    - assets/images/baredex-logo.png
    - assets/images/baredex-logo-big.png
    - assets/images/flags/au.png
    - assets/images/flags/fr.png
    - assets/images/flags/kw.png
    - assets/images/flags/om.png
    - assets/images/flags/sa.png
    - assets/images/flags/ae.png
    - assets/images/flags/gb.png
    - assets/images/flags/us.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700